name: flutter_webrtc_demo
description: A new Flutter application.
version: 1.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  date_format: ^2.0.5
  cupertino_icons: ^1.0.4
  google_fonts: ^2.2.0
  flutter_webrtc: ^0.8.1
  shared_preferences: ^2.0.12
  http: ^0.13.4
  path_provider: ^2.0.8
  intl: ^0.17.0
  flutter_image_compress: ^1.1.0
  image_picker: ^0.8.4+4
  path: ^1.8.0
  image_cropper: ^1.4.1
  email_validator: ^2.0.1
  firebase_auth: ^3.3.5
  firebase_database: ^9.0.5
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  json_annotation: ^4.4.0
  image: ^3.1.1
  firebase_auth_web: ^3.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logoist.jpg
    - images/no_photo_selected.png
    - images/bank_NTBS.png